FROM node:lts as packages
WORKDIR /root/src
RUN --mount=target=/context cd /context; \
  find . '(' -name package.json -or -name package-lock.json ')' -exec cp --parents {} /root/src ';'

FROM node:lts
WORKDIR /root/src
COPY --from=packages /root/src .
RUN npm install -g npm
RUN npm install ; npm ci
