version: '3'
services:
  builder-image:
    image: olympus-node
    build:
      context: .
      dockerfile: Dockerfile.base

  postgres-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - '${ENV:-dev}.env'
      - ./docker-secrets/db.env

networks:
  services_leapx:
    external: false
